### PR TITLE
Optimise features to reduce binary size

### PR DESCRIPTION
**Pull request by jirutka**
Please see the commit messages.

### CODE REVIEW

**Comment by Kirottu** [comment]
Optimizing the features I get, but what's the practical benefit of making webp optional?

**Comment by jirutka** [comment]
The benefit is that you do `cargo build --release --locked --no-default-features` and build watershot without webp and without the need to edit `Cargo.toml` and update `Cargo.lock`.

**Comment by Kirottu** [comment]
Yes, but what's the practical benefit of disabling benefit aside from just cutting down on dependencies?

**Comment by jirutka** [comment]
Well, cutting down the binary size and also reducing the attack vector.

**Comment by Kirottu** [comment]
I really don't see the value in that for a project like this, the binary size difference is probably negligible when it comes to modern storage anyway.

**Comment by jirutka** [comment]
That’s just a matter of opinion. You can omit the last commit adding the webp feature.

**Pull request merged**
